---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: us-east-2
  version: '1.16'  
managedNodeGroups:
  - name: capstone
    instanceType: t2.large
    minSize: 2

nodeGroups:
  - name: capstone
    instanceType: m5.large
    minSize: 2
    volumeSize: 100
    amiFamily: WindowsServer2019FullContainer
    privateNetworking: false
