apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: capstone
        image: nouranelkassas/capstone
        ports:
        - containerPort: 80
