apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: nouranelkassas/capstone
        ports:
        - containerPort: 8080
volumeMounts:
          - name: jenkins-home
            mountPath: /usr/share/jenkins
      volumes:
        - name: jenkins-home
          emptyDir: {}
